# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4ba4e2d0059e86b267a698679c62e170a1ec12f55d821860066c15b618516298d6d932dcf3372e854e8d7a36d470ec60093b3297d887e3f527430f847b59f71a

test:
  secret_key_base: ddfd4f53181e302721b7bfa7c5abcbb00d96fdb9cc604b475ddce271bad90692e55e4ac3274829b2796afeeebc4a53b1821a16c65fb53236e19791938c7acb61

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
